### ISSUE TITLE
Plugin does not work on some systems

### ISSUE THREAD

**Issue by Quanteey** [MGW14/FFA-Reloaded#2]
Details unknown.
The plugin does not work on my remote server host and my machine, although it is the 1:1 copy of the server that worked on MGW14's system.

The issue occurs when trying to reload or load new maps.

**Comment by MGW14** [comment]
I'm sorry, but I was unable to reproduce this issue. Please attach Log Files so I can help you out easier.
- Issue closed due to unreproducability -
